version: "3.6"

services:
  # DB #
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fsdb
      POSTGRES_USER: fsdb
      POSTGRES_PASSWORD: fsdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "9500:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: admin
        PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - ./pgadmin:/root/.pgadmin
    ports:
        - "9501:80"
